environment:
  PYTHON: "C:\\Python37"
  REPOSITORY_KEY:
    secure: 3jorWUxqWjnR0X8Ye5NsAurPzickp84H2a+/ILwlRA3EQXzv+jo+kv9tvI1YKyTE
    secure: MpbD7FQXYeXhUYV99nILNF66c1Y+QtxKGEc+TUkXVNo=
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  matrix:
    - CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
    - CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Debug
    - CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: RelWithDebInfo
    - CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: MinSizeRel

cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform: x64

install:
  - git submodule update --init --recursive
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  # Conan
  - cmd: pip.exe install conan --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: pip.exe install conan_package_tools --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: refreshenv
  - cmd: conan user # It creates the conan data directory

build_script:
  - cmd: conan --version
  - cmd: python build.py %REPOSITORY_KEY% %REPOSITORY_URL%