language: cpp
notifications:
  email: false
sudo: false
dist: trusty
services:
- docker
matrix:
  include:
  - os: linux
    compiler: clang
    env: CXX=clang++ CC=clang
  - os: linux
    compiler: gcc
    env: CXX=g++ CC=gcc
script:
- docker run -e "CI" -e "TRAVIS" -e "TRAVIS_TAG" -e "TRAVIS_BUILD_NUMBER" -e "CXX"
  -e "CC" -e "REPOSITORY_KEY" -e "REPOSITORY_URL" --tty=false -it -v $PWD:/src --workdir
  /src bentou/ubuntu-bionic-dev python3 ./build.py
before_script:
- docker pull bentou/ubuntu-bionic-dev
- docker ps -a
- mkdir bin
env:
  global:
  - secure: cKeA07aGPC7ZnNg2oZEvusgl7mN/WNGaydMott6rRn0vgxBR1VxDsmXoZ05ZzO/G5zmKrG1EVyCar0FTK8NsfDwDY0W3oa0IHPeQJch2pNh+fnbWGqoWfCsxdLESilR/FirP2UOdmFO2/D7IFYRJqTLGGg7P7+U89PfrOOpScxWGD1O+MKH4IAV2q1rJDe7QJAha8H+CxpHTzOrUULIieAF6h51my9QGIOqjOYeW0dh/BlEiqzXqSIZP22kbXH9KlV4trPw2y7w8eUxdYd9ShzbF+UckvdWGCVo4WWHPJwFlC594akPxMAfro8VaX8YYjUsr9WLpIfsRX0wtQgkZGqvjQ4/9J20cGYescqfQSa6vDtUsNVmXp7XfkxLDXpTVjtBJ0HWuUqrIp0Tl40ohQLeDdkVuhKgc1fJLmAQE9MGnI9siXBCrderrbLRIA/bSxC8l/LwSMM8NOKAF6IWaO+zc78FgUymJ/OsTqflbO/BOkpTokJcUZMDMWOluwyqNKlsesrCIMypYXX3w7/Ez798doWSjKTtkcARgveGTrQueTYa9iRHqMnduJLPJ2v+y4TEsmYAYQILKyYnu+/2Q9+tccasd69VY2DBWIRCtbDG5c32hQmH471O/YpJBqKFSiIS7IF/ZzxOi2ke1ZgZOK+DdSQanTHfX2vr1F5bbuoU=
  - secure: kJn8IDoKfmVREaUzfAgPR3kErXdTUxEJWGKQMuSnPlCad07j8euYwa9OhBrfgByxKajOkAx13BkASWipgV7rQVbWXdhnzvTlEMlz75tY51yVtyOg5idGsd/0nDUxMioHVpNCdTMu54nWCz3m6XMFgoz7eTvtBL1E9+DCY+yN0xendupPDMjJhObPeDuVQUJAB/9If0VRAyhV+LMSa2FjaXFY+tCdYvZiR4cLceqmHsZYnAxEnzd1Akfr4fccGvBbf7L5cxzOXTW++zKtxplhS9ZdW0ZAp5O2cItPh+qyoY62ZZmPca8EfV9TylcQiuOTvHQlf8wHw9CUwsL+tMFy5qEKQMK3SUqrxak70Q9cnUrlQfj52C0ClAYrSnMWnhOJJo2EIR0nYqapRj6a3MyXU3A6ClRCzH/M3ny4gc073yyVxeIGIQw6OCq8qt38kNTu5Bm0hBGgLr6CZivMzF3RZO8PPdT8/AH+H5WrKTS7tfVgYf83h2XzEZ8XhskKy77mQCMFjsXXSU/DWuZE7L/xqtK3pe9EMXpG3qf0pUsROneb8MHibI4d0AL5VKQcUm0RUt1+HG1XD/BBoAuSurHtDI1a6NEC5DhrnnNz+IsdkswfDJp3W8Qt9g3Z0K9x5rKCto7k+LhRH24G1iHwu3uxGaC+A89vkvF3CIcR+er1zTI=
