language: cpp
notifications:
  email: false
sudo: false
dist: trusty
services:
- docker
matrix:
  include:
  - os: linux
    compiler: clang
    env: CXX=clang++ CC=clang
  - os: linux
    compiler: gcc
    env: CXX=g++ CC=gcc
script:
- docker run -e "CI" -e "TRAVIS" -e "TRAVIS_TAG" -e "TRAVIS_BUILD_NUMBER" -e "CXX"
  -e "CC" -e "REPOSITORY_KEY" -e "REPOSITORY_URL" --tty=false -it -v $PWD:/src --workdir
  /src bentou/ubuntu-bionic-dev python3 ./build.py
before_script:
- docker pull bentou/ubuntu-bionic-dev
- docker ps -a
- mkdir bin
env:
  global:
  - secure: Y6SE57suYkcAJR+J8AJbOJlMy9EYQLF1K7lqVh5bL+nz+L+SUSuzQVEOzqb5J/1lLA2fb038hvHj8bFgk2cUfaZW/jwN22FM7HfSQe19lKxZWiq8+N+mDlIQLvMkOCaEnmEa9nmqNN/dT3bR8X7aD2kId9gZq2/ra1JC5jtJcVPhykli0dmekiW1Htjab9/mHUhkB/V8pP3vQt+uU3beVmscDp2cZ7/wbi5MXIxtMhriS6sr8ITbBPOqF9DC+bxMVh5W6tgf26kauKCRefdgMuIFU6Ud1secA1Qo50tPW3x5MCZ4cpBJ5iqh1PsjErug13EogENEb2+z8N4txDCRpM3lKcFci5R86ek01fqL3IQ0gLuGRwl260CZGAe9k20re/jKcb2byviglEQj5Bm5zj+iBvMoA8CoQO9VFGIwHhxc+7bhZRZ+xlyXfXs00BQidASw+UoaSRg6/rPrQQuuN/ga3E+xXPujtEciuQOIxyUD3NhN83o7JwJLSOjZg7J+a4023G3TgyEltqTmbC611kt/zG6RtqmX+4mgkMrIMq3wOphzNOA/zKSstUafzIGMCidulDm4umcFUIPjuDuLjaooNDDk6BWEBANF+LMYUO4J1NDH3F3E9XXIjsBqhvI/M2j04riptV5fXZrR52bS/BHgy+6kxIHz3HZxiDeRrYs=
  - secure: GcYDDoPDjUtf4Su2zm1dyT7dYLrfIdQEQtkaiHNIIcAzuoC0iWnDzyOJZZWPcjYAiR6cd0afSt757xh7rajfG7qwbL/kHp5JG3w/dY+Wnr8b6PwYuH/xPe6dEG0LDhz5moCx9s7a8f/I5AOYreze92fwMGun8tVP178UHiwlytfb9N+J4szxNFGcHe4j3NASHMbOIA68CvLbgsIjmT+CxMLE+VN8gUI6H+zJcsV0128SUAzgbiuBOU0xvkLLQS3AkRHolql04Rk6PahgeiedwZsNOZlDKRNSOOTnSD1RppMSAGN1t7wJl+9Hil6Yx6OPdj7RDl9GuPjPR+gU2W36TYE/AbZ2OQjH1Ti1s2sKp2/YZjUnXtkeQLESfZzqmerxhtBX2vt0/924of9HV2ZVwbvCF2ha1FdxoQBnM5e7mjC7Mwf1Q02Ug5cevKv6iwKghT/Qstc0yFYEb807hb0XCAA0/IuNM20lZC/5TRYYOZ7b0rZtGap262cEbrZFE4fVun4NgkBr4a/NGfIe7LLvQzdAUrCtNgLBGmcjwabsYVep+h8NWBP9gG+Jnr3CoQLRcpouKTEM8SWM0wIM8cbLRt0MbvFHXO4TceZ9Q1swCsf021K6bvWGsDhnN/1d1b8dJCQCdiUGrvYSBL52V1fvcPPR8iQ2NTmn+e1LsaS2NNE=
